### PR TITLE
Fix a cmake overlook with spaces in project path

### PR DESCRIPTION
**Pull request by steelshot**
Great job in the initial port, just a small overlook i've found trying this out

### CODE REVIEW

**Comment by netship02** [comment]
@multiplemonomials @SteelShot Can you please look at my issue on https://github.com/mit-pdos/xv6-public/pull/117

**Comment by multiplemonomials** [comment]
Good catch.  Dangit, I actually had this same exact issue on another project with a linker script!

@netship02 it looks to me like this may be an issue with using the latest version of Binutils.  Does the Makefile build work OK?

**Comment by netship02** [comment]
@multiplemonomials Yeah 'make' work and make qemu-nox launches kernel fine.

Update: Downgrading Binutils (2.34-2 -> 2.33.1-2) fixes the problem.

**Comment by multiplemonomials** [comment]
Hmm, interesting

**Comment by netship02** [comment]
@multiplemonomials But now if i use cmake and then make qemu then it stucks at "Booting from hard disk" even after using this [patch](https://github.com/mit-pdos/xv6-public/pull/115)
But normal make without using cmake works fine with above [patch](https://github.com/mit-pdos/xv6-public/pull/115)

Here are "objdump -x kernel" output of generated kernel image
[original(without cmake)](https://pastebin.com/MrpJt2c2)
[Cmake](https://pastebin.com/AvgMqBHS)

I think both build will has to produce same kernel? But both are different.

**Comment by multiplemonomials** [comment]
Oh man you're in luck!  I just ran into this exact same issue on my system, finally figured it out.  Looks like the issue is that it was passing -no-pie to the C compiler but not the ASM compiler, and I hadn't tested with a PIE system until now.  Just pushed a fix, it should fix both the PHDR segment error and the failure to boot.

**Comment by netship02** [comment]
Just checked It works!
But now i am getting this error `com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: Remote 'g' packet reply is too long (expected 312 bytes, got 608 bytes): 0000000000000000000000000000000000000000000000006306000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f0ff0000000000000200000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000060000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007f0300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000801f0000
Debugger disconnected
`

**Comment by multiplemonomials** [comment]
Hmm... Are you using clion-included GDB or system GDB?  What version is it?  Try switching to the other one.

**Comment by multiplemonomials** [comment]
Also, what qemu executable are you using?  It prints the path in the CMake build report.

**Comment by netship02** [comment]
```
`home/netship/clion-2020.1.1/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /home/netship/CLionProjects/xv6-public
-- The C compiler identification is GNU 9.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- The ASM-ATT compiler identification is GNU
-- Found assembler: /usr/bin/as
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Compatible elf32-i386 GCC compiler detected.
-- Performing Test SUPPORTS_FNO_STACK_PROTECTOR
-- Performing Test SUPPORTS_FNO_STACK_PROTECTOR - Success
-- Performing Test SUPPORTS_NO_PIE
-- Performing Test SUPPORTS_NO_PIE - Success
-- CLion detected, creating CLion .gdbinit
-- 
-- xv6 configuration complete.
-- -----------------------------------------
-- Build Type: Debug
-- 
-- C Compiler: GNU 9.3.0 (/usr/bin/cc)
-- C Flags: -m32 -fno-pic -fno-builtin -fno-strict-aliasing -Wall -Werror -fno-omit-frame-pointer -nostdinc -fno-stack-protector -no-pie 
-- 
-- ASM Compiler: GNU (/usr/bin/as)
-- ASM Flags: -m32 -gdwarf-2 -Wa,-divide -no-pie 
-- 
-- Linker Flags: -nostdlib -Wl,-m,elf_i386 -Wl,--build-id=none
-- 
-- QEMU Executable: /usr/bin/qemu-system-x86_64
-- QEMU runs will use 2 processors.
-- -----------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/netship/CLionProjects/xv6-public/cmake-build-debug

[Previous CMake output restored: 5/10/20, 12:30 PM]
`
```
Let me test using different gdb

**Comment by multiplemonomials** [comment]
Aha, found the problem: /usr/bin/qemu-system-x86_64
Some searching shows that while this version will work for running it may not work for debugging, I normally use qemu-system-i386

**Comment by multiplemonomials** [comment]
Also btw things like this will be a lot easier to read if you post them in code blocks.  Use three backticks to start and end one.

**Comment by multiplemonomials** [comment]
Actually, first try this:
Find this line in your xv6-public/.gdbinit:
```
set architecture i386
```
Add replace it with this:
```
set arch i386:x86-64
```

**Comment by multiplemonomials** [comment]
Careful to not rerun cmake after this change or it will overwrite it

**Comment by netship02** [comment]
Finally worked!! 
Using qemu-system-i386 fixes the problem. Thank you!!!

**Pull request merged**
